# Generated by Django 6.0.3 on 2026-03-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_attachment_created_by_chat_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='admin_users',
            field=models.ManyToManyField(blank=True, related_name='admin_users', to='main.user'),
        ),
    ]
